blueprint:
  name: Test Number Set Value
  description: Test blueprint for number.set_value with dynamic entity_id
  domain: automation
  input:
    tesla_device:
      name: Tesla BLE Device
      description: 2-Select the ESPHome-provided device.
      selector:
        device:
          integration: esphome
  variables:
    device_id: !input tesla_device
trigger:
  - platform: mqtt
    topic: ha-evcc/1/test
    id: test_trigger
action:
  - condition: template
    value_template: "{{ trigger.id == 'test_trigger' }}"
  - action: number.set_value
    data:
      value: 10
    target:
      entity_id: "{{ device_entities(device_id) | select('match', 'number.*_charging_amps$') | first }}"
