automation:
  - alias: Octopus Charging with evcc
    description: Automates charging using Octopus Energy intelligent dispatching and evcc mode control
    trigger:
      - platform: state
        entity_id: binary_sensor.octopus_a_38af7435_intelligent_dispatching
        to: "on"
    condition: []
    action:
      - service: select.select_option
        target:
          entity_id: "{{ device_entities('evcc_heidelberg') | select('match', '.*_mode$') | first }}"
        data:
          option: now
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: select.select_option
        target:
          entity_id: "{{ device_entities('evcc_heidelberg') | select('match', '.*_max_current$') | first }}"
        data:
          option: 16
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.octopus_a_38af7435_intelligent_dispatching
            to: "off"
            for:
              hours: 0
              minutes: 0
              seconds: 5
        timeout:
          hours: 5
          minutes: 0
          seconds: 0
          milliseconds: 0
      - service: select.select_option
        target:
          entity_id: "{{ device_entities('evcc_heidelberg') | select('match', '.*_mode$') | first }}"
        data:
          option: pv
    mode: restart
