blueprint:
  name: EVCC Octopus Test Integration
  description: Blueprint für die EVCC-Octopus-Test-Integration mit auswählbarem Sensor
  domain: automation
  input:
    octopus_sensor:
      name: Octopus Intelligent Dispatching Sensor
      description: Wählen Sie den binary_sensor aus, der von der octopus_germany Integration bereitgestellt wird.
      selector:
        entity:
          domain: binary_sensor
          integration: octopus_germany
trigger:
  - platform: state
    entity_id: !input octopus_sensor
    to: "on"
condition: []
action:
  - device_id: cc674e67e3d095e4b92ccb5ca609e6f9
    domain: select
    entity_id: 990b75ec11c14f42a593cc7464f4afe7
    type: select_option
    option: "16"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - device_id: cc674e67e3d095e4b92ccb5ca609e6f9
    domain: select
    entity_id: aa2b6c2cce923edce6aee2dae73456c4
    type: select_option
    option: now
  - wait_for_trigger:
      - platform: state
        entity_id: !input octopus_sensor
        to: "off"
        for:
          hours: 0
          minutes: 0
          seconds: 5
    timeout:
      hours: 5
      minutes: 0
      seconds: 0
      milliseconds: 0
  - device_id: cc674e67e3d095e4b92ccb5ca609e6f9
    domain: select
    entity_id: aa2b6c2cce923edce6aee2dae73456c4
    type: select_option
    option: pv
mode: single
