blueprint:
  name: EVCC Octopus Germany Integration
  description: Blueprint für die Octopus-Integration mit auswählbarem Sensor und Gerät. Stellt sicher, dass EVCC mit Ladevorgängen kooperiert, die Octopus auslöst.
  domain: automation
  input:
    octopus_sensor:
      name: Octopus Intelligent Dispatching Sensor
      description: Wählen Sie den binary_sensor aus, der von der octopus_germany Integration bereitgestellt wird.
      selector:
        entity:
          domain: binary_sensor
          integration: octopus_germany
    evcc_device:
      name: EVCC Gerät
      description: Wählen Sie das Gerät aus, das von der evcc_intg Integration bereitgestellt wird.
      selector:
        device:
          integration: evcc_intg
trigger:
  - platform: state
    entity_id: !input octopus_sensor
    to: "on"
condition: []
action:
  - device_id: !input evcc_device
    domain: select
    entity_id: 990b75ec11c14f42a593cc7464f4afe7
    type: select_option
    option: "16"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - device_id: !input evcc_device
    domain: select
    entity_id: aa2b6c2cce923edce6aee2dae73456c4
    type: select_option
    option: now
  - wait_for_trigger:
      - platform: state
        entity_id: !input octopus_sensor
        to: "off"
        for:
          hours: 0
          minutes: 0
          seconds: 5
    timeout:
      hours: 5
      minutes: 0
      seconds: 0
      milliseconds: 0
  - device_id: !input evcc_device
    domain: select
    entity_id: aa2b6c2cce923edce6aee2dae73456c4
    type: select_option
    option: pv
mode: single
