blueprint:
  name: Octopus Charging with evcc Support
  description: Automates charging using Octopus Energy intelligent dispatching and evcc mode control
  domain: automation
  input:
    octopus_sensor:
      name: Octopus Energy Sensor
      description: Select the Octopus Energy intelligent dispatching sensor
      selector:
        entity:
          integration: octopus_germany
          domain: binary_sensor
    evcc_device:
      name: evcc Device Mode
      description: Select the evcc device mode entity
      selector:
        entity:
          integration: evcc*
          domain: binary_sensor
trigger:
  - platform: state
    entity_id: !input octopus_sensor
    to: "on"
condition: []
action:
  - action: select.select_option
    metadata: {}
    data:
      option: now
    target:
      entity_id: !input evcc_device
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - action: select.select_option
    metadata: {}
    data:
      option: 16
    target:
      entity_id: !input evcc_device
  - wait_for_trigger:
      - platform: state
        entity_id: !input octopus_sensor
        to: "off"
        for:
          hours: 0
          minutes: 0
          seconds: 5
    timeout:
      hours: 5
      minutes: 0
      seconds: 0
      milliseconds: 0
  - action: select.select_option
    metadata: {}
    data:
      option: pv
    target:
      entity_id: !input evcc_device
mode: restart
