blueprint:
  name: Tesla EVCC MQTT Status (Entity-Selector, Endung gefiltert)
  description: >
    Sendet SOC, SOC-Limit, Reichweite und Ladezustand eines Tesla-Fahrzeugs per MQTT.
    Nutzer wählt nur die Haupt-Entität aus. Andere Entitäten werden automatisch abgeleitet.
  domain: automation

  input:
    main_entity:
      name: Haupt-Entität des Fahrzeugs
      description: Wähle den Sensor (z. B. Charging State) oder Schalter (Charger). Alle anderen Sensoren werden automatisch abgeleitet.
      selector:
        entity:
          domain: sensor
          filter:
            name: ".*Charging State$"   # Filter auf Endung
    mqtt_prefix:
      name: MQTT Topic Prefix
      description: Basis-Topic für alle Statusmeldungen
      default: ha-pv/1
      selector:
        text:

trigger:
  - platform: time_pattern
    seconds: /10

action:
  - variables:
      # Präfix aus der Haupt-Entität ableiten
      prefix: "{{ main_entity.rsplit('_', 1)[0] }}"

      # Alle relevanten Sensoren
      soc_sensor: "{{ p_
