blueprint:
  name: Tesla BLE EVCC Communication
  description: Publishes Tesla BLE sensor states to MQTT every 10 seconds and controls a wallbox based on MQTT messages.
  domain: automation
  input:
    tesla_device:
      name: Tesla Device
      description: Select the Tesla device to monitor and control.
      selector:
        device:
    wb_enable_topic:
      name: Wallbox Enable Request Topic
      description: The MQTT topic to subscribe to for enabling/disabling the wallbox.
      selector:
        text:
          type: text
      default: ha-evcc/1/wb-enable-request
    max_charge_topic:
      name: Max Charge Requested Topic
      description: The MQTT topic to subscribe to for setting the max charge current.
      selector:
        text:
          type: text
      default: ha-evcc/1/max-charge-requested
    instance_number:
      name: Instance Number
      description: The number to use in MQTT topic paths (e.g., ha-evcc/<number>/...). Use this if you have multiple Teslas.
      selector:
        text:
          type: text
      default: "1"
  source_url: https://example.com/tesla_ble_mqtt_combined.yaml
trigger:
  - platform: time_pattern
    seconds: /10
    id: publish_sensors
  - platform: mqtt
    topic: !input wb_enable_topic
    id: wb_enable_request
  - platform: mqtt
    topic: !input max_charge_topic
    id: max_charge_requested
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'publish_sensors' }}"
        sequence:
          - alias: MQTT publish Tesla charge limit
            action: mqtt.publish
            data:
              qos: 0
              retain: false
              topic: ha-evcc/{{ instance_number }}/tesla-soc-limit
              payload: "{{ states(device_entities(device_id) | select('match', '.*_charge_limit$') | first)|int }}"
            metadata: {}
          - alias: MQTT publish Tesla range
            action: mqtt.publish
            data:
              qos: 1
              retain: false
              topic: ha-evcc/{{ instance_number }}/tesla-range
              payload: "{{ states(device_entities(device_id) | select('match', '.*_range$') | first)|int }}"
            metadata: {}
          - alias: MQTT publish Tesla charge status
            action: mqtt.publish
            data:
              qos: 1
              retain: false
              topic: ha-evcc/{{ instance_number }}/tesla-charge-status
              payload: >-
                {{
                {"Disconnected":"a","Ready":"b","Charging":"c","Stopped":"d","No Power":"b","Complete":"b","Error":"f"}[states(device_entities(device_id) | select('match', '.*_charging_state$') | first)]
                }}
            metadata: {}
            enabled: true
          - alias: MQTT publish Tesla odometer
            action: mqtt.publish
            data:
              qos: 0
              retain: false
              topic: ha-evcc/{{ instance_number }}/tesla-odometer
              payload: "{{ states(device_entities(device_id) | select('match', '.*_odometer$') | first)|int }}"
            metadata: {}
          - alias: MQTT publish Tesla finish time
            action: mqtt.publish
            data:
              qos: 1
              retain: false
              topic: ha-evcc/{{ instance_number }}/tesla-finishtime
              payload: >
                {% set ts = now().utcnow() + timedelta(minutes=states(device_entities(device_id) | select('match', '.*_minutes_to_limit$') | first)|int) %}
                {{ ts.strftime("%Y-%m-%dT%H:%M:%SZ") }}
            metadata: {}
          - alias: MQTT publish Tesla SOC
            action: mqtt.publish
            data:
              qos: 1
              retain: false
              topic: ha-evcc/{{ instance_number }}/tesla-soc
              payload: "{{ states(device_entities(device_id) | select('match', '.*_charge_level$') | first)|float }}"
            metadata: {}
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'wb_enable_request' }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ trigger.payload | bool }}"
            then:
              - action: switch.turn_on
                metadata: {}
                data: {}
                target:
                  entity_id: "{{ device_entities(device_id) | select('match', 'switch.*_charger$') | first }}"
            else:
              - action: switch.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id: "{{ device_entities(device_id) | select('match', 'switch.*_charger$') | first }}"
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'max_charge_requested' }}"
        sequence:
          - action: number.set_value
            data:
              value: "{{ trigger.payload | int }}"
            target:
              entity_id: "{{ device_entities(device_id) | select('match', 'number.*_charging_amps$') | first }}"
variables:
  device_id: !input tesla_device
  instance_number: !input instance_number
mode: single
