blueprint:
  name: Tesla BLE EVCC Communication
  description: Publishes Tesla BLE sensor states to MQTT every 10 seconds and controls a wallbox based on MQTT messages.
  domain: automation
  input:
    tesla_device:
      name: Tesla BLE Device
      description: Select the Tesla device to monitor.
      selector:
        device:
    wb_enable_topic:
      name: Wallbox Enable Request Topic
      description: The MQTT topic to subscribe to for enabling/disabling the wallbox.
      selector:
        text:
          type: text
      default: ha-evcc/1/wb-enable-request
    max_charge_topic:
      name: Max Charge Requested Topic
      description: The MQTT topic to subscribe to for setting the max charge current.
      selector:
        text:
          type: text
      default: ha-evcc/1/max-charge-requested
    wallbox_switch:
      name: Wallbox Switch
      description: Select the switch entity for enabling/disabling the wallbox.
      selector:
        entity:
          domain: switch
    wallbox_current:
      name: Wallbox Current Number
      description: Select the number entity for setting the max charge current.
      selector:
        entity:
          domain: number
    notify_entity:
      name: Notification Entity (Optional)
      description: Select the notification entity to send messages (leave empty to disable notifications).
      selector:
        entity:
          domain: notify
      default: ""
  source_url: https://example.com/tesla_ble_mqtt_combined.yaml
trigger:
  - platform: time_pattern
    seconds: /10
    id: publish
